### ISSUE TITLE
Issue updating plugin from Wordpress's Plugin interface

### ISSUE THREAD

**Issue by Shaderpixel** [AxeWP/wp-graphql-gravity-forms#386]
### Description

When updating the plugin through WP's admin Plugin interface, the following error occurs:

<img width="926" alt="wpgf-updateissue" src="https://github.com/AxeWP/wp-graphql-gravity-forms/assets/12938414/966ade2f-ccb6-47d5-82b1-1d2ec5608ffb">

Downloading the package and manually update it through FTP works fine. Currently on WPengine Atlas, with WP version 6.3 and PHP 8.0. Let me know if I missed out any important information.

### Steps to reproduce

1. Go to the Plugins page in WP admin
2. Select Update underneath WPGraphQL for Gravity Forms
3. Observe error message appear like in attached screenshot in Description

### Plugin Version

0.12.0

### Gravity Forms Version

2.7.14

### WordPress Version

6.3

### WPGraphQL Version

1.16.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [ ] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by brandensilva** [comment]
Seeing same issue

**Comment by justlevine** [comment]
Hey @Shaderpixel @brandensilva 

I believe I've fixed this in #388. The annoying part is that you'll still need to manually update to v0.12.4 (once it's released), but if you want, you can checkout that PR and follow the testing instructions to confirm its working for you as well.

**Comment by brandensilva** [comment]
Thanks @justlevine for the quick turn around on this one! And of course I'm not alone is saying I appreciate all the work you do with bringing the best of WordPress plugins via WPGraphQL to make headless a reality for many of us.

I'm heading out for the weekend but if you haven't already merged in your changes by then, and I find some time next week, I'll be sure to check it out the PR. Maybe @Shaderpixel will beat me too it. Have a great weekend!
