### ISSUE TITLE
defaultValue for Email field doesn't work

### ISSUE THREAD

**Issue by Gytjarek** [AxeWP/wp-graphql-gravity-forms#391]
### Description

Email field doesn't return `defaultValue`. Works when confirmation email is used though. 

### Steps to reproduce

Assign defaultValue for the email field

### Plugin Version

0.12.4

### Gravity Forms Version

2.7.8

### WordPress Version

6.3.1

### WPGraphQL Version

1.16.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [ ] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @Gytjarek

Thanks for flagging this - got it fixed in #394

**Comment by justlevine** [comment]
And released in [v0.12.5](https://github.com/AxeWP/wp-graphql-gravity-forms/releases/tag/v0.12.5)

**Comment by adam-ainsworth** [comment]
Hi,

I don't think this has been fixed - defaultValue still isn't in the fields on an email input (see attached)

I had a little play with the code and it doesn't look like the patch is being called

I'm happy to try further tests if needed

Thanks

![image](https://github.com/AxeWP/wp-graphql-gravity-forms/assets/554151/87d2afd9-f9d1-42f9-a9ff-723777815c52)

**Comment by justlevine** [comment]
Hey @adam-ainsworth 👋

The `defaultValue` should be available on the [`field.inputs` array](https://github.com/AxeWP/wp-graphql-gravity-forms/blob/c30957817876c92448fe244256d6aaa8c60be8d7/src/Type/WPInterface/FieldInputSetting/InputWithEmailConfirmation.php#L40).

I'm overseas on location for a client this week, but let me know if it's not working and I'll dive in once I'm back.

**Comment by adam-ainsworth** [comment]
Hi @justlevine - thanks for getting back to me and apologies for disturbing you while you're away. I'm afraid I'm not seeing it, with either the single email field or with the confirmation field activated

![image](https://github.com/AxeWP/wp-graphql-gravity-forms/assets/554151/2e3642ca-95e6-46e7-bf9c-40a3af2434d4)

I am running on the latest version (0.12.5) of the plugin

Absolutely no rush on this, so just whenever it is convenient - thanks again :-)

**Comment by justlevine** [comment]
No disturbances at all, was just setting expectations 😎

Im pretty sure `defaultValue` is applied via a specific interface, which is why you're not seeing it there. Would need to be `... on GfFieldInputWithEmailConfirmationSetting { defaultValue }` or something similF.

Hopefully if you open the documentation explorer on the right side of the IDE and search `defaultValue` you'll be able to find exactly where that field is applied to the GraphQL object. As soon as I'm by my desk I'll try and share a repl 🤞

**Comment by adam-ainsworth** [comment]
Ah yes - that's got it

![image](https://github.com/AxeWP/wp-graphql-gravity-forms/assets/554151/4324233b-4be7-4c81-ace0-52155f15970b)

Thanks very much for your help!
