### ISSUE TITLE
Filtering Query by pageNumber

### ISSUE THREAD

**Issue by SamuelHadsall** [AxeWP/wp-graphql-gravity-forms#392]
### Description

Trying to filter form fields by page number if form has paging data.

### Steps to reproduce

1. Create form with page breaks, with any number of fields
2. Go to Graphical IDE
3. In Query window, create new query using gfForm and pass the id of the form where a pageNumber equals like 2.
4. Doing so continues to return all form fields and not just fields on page 2.
5. I would expect that it would only return the fields on page 2 and not all fields again.

![image](https://github.com/AxeWP/wp-graphql-gravity-forms/assets/6413981/600436f0-8b55-49e9-9aef-5526af54d098)

Here is the schema that I am using:

`query getForm($id: ID!, $pageNumber: Int!) {
  gfForm(id: $id, idType: DATABASE_ID) {
    databaseId
    title
    description    
    submitButton {
      conditionalLogic {
        actionType
        logicType
        rules {
          fieldId
          operator
          value
        }
      }
      location
      text
      type
      width
    }
    confirmations {
      isDefault
      message
    }
    formFields(where: {pageNumber: $pageNumber}) {
      nodes {
        id
        type
        pageNumber
        ... on AddressField {
          ...AddressFieldFields
        }
        ... on CheckboxField {
          ...CheckboxFieldFields
        }
        ... on DateField {
          ...DateFieldFields
        }
        ... on EmailField {
          ...EmailFieldFields
        }
        ... on MultiSelectField {
          ...MultiSelectFieldFields
        }
        ... on NameField {
          ...NameFieldFields
        }
        ... on PhoneField {
          ...PhoneFieldFields
        }
        ... on RadioField {
          ...RadioFieldFields
        }
        ... on SelectField {
          ...SelectFieldFields
        }
        ... on TextField {
          ...TextFieldFields
        }
        ... on TextAreaField {
          ...TextAreaFieldFields
        }
        ... on TimeField {
          ...TimeFieldFields
        }
        ... on WebsiteField {
          ...WebsiteFieldFields
        }
      }
    }
    nextFieldId
    pagination {
      type
      style
      color
      hasProgressbarOnConfirmation
      backgroundColor
      lastPageButton {
        text
      }
    }
    lastPageButton {
      text
      type
    }
  }
}`

Here are my fragments
`fragment AddressFieldFields on AddressField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  inputs {
    ... on AddressInputProperty {
      key
      label
      placeholder
      isHidden
    }
  }
  visibility
  pageNumber
}

fragment CheckboxFieldFields on CheckboxField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  hasSelectAll
  inputs {
    id
  }
  choices {
    text
    value
  }
  pageNumber
}

fragment DateFieldFields on DateField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  placeholder
  pageNumber
}

fragment EmailFieldFields on EmailField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  placeholder
}

fragment MultiSelectFieldFields on MultiSelectField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  choices {
    text
    value
  }
  pageNumber
}

fragment NameFieldFields on NameField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  inputs {
    ... on NameInputProperty {
      key
      label
      placeholder
      choices {
        text
        value
      }
    }
  }
  pageNumber
}

fragment PhoneFieldFields on PhoneField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  placeholder
}

fragment RadioFieldFields on RadioField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  choices {
    text
    value
  }
  pageNumber
}

fragment SelectFieldFields on SelectField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  defaultValue
  choices {
    text
    value
  }
  pageNumber
}

fragment TextAreaFieldFields on TextAreaField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  pageNumber
}

fragment TextFieldFields on TextField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  placeholder
  conditionalLogic {
    actionType
    logicType
    rules {
      fieldId
      operator
      value
    }
  }
  pageNumber
}

fragment TimeFieldFields on TimeField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
}

fragment WebsiteFieldFields on WebsiteField {
  id
  databaseId
  label
  description
  cssClass
  isRequired
  placeholder
  pageNumber
}`

### Plugin Version

0.12.4

### Gravity Forms Version

2.8.2

### WordPress Version

6.4.2

### WPGraphQL Version

1.20.0

### Additional enviornmental details

PHP version | 7.4.33.4

Using Faustjs, along side local development (localhost:3000) and Atlas.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Accidentally tagged in a different PR 🤦. Fix coming in #395

**Comment by justlevine** [comment]
Thanks for reporting this @SamuelHadsall , it's fixed in [v0.12.5](https://github.com/AxeWP/wp-graphql-gravity-forms/releases/tag/v0.12.5)

**Comment by SamuelHadsall** [comment]
Awesome! Thanks @justlevine! No problem, happy to help.
