### ISSUE TITLE
How can i show form entries to non-auth users?

### ISSUE THREAD

**Issue by edikamy** [AxeWP/wp-graphql-gravity-forms#393]
### Description

I want to implement feedback for my users
i use a form for get feedbacks and now i want to show other users feedback in feedback page
but list of submitted entries just accessible with authenticated users
i couldn't find any way to do this

my Question is:
How can i show form entries to non-auth users as public?

### Steps to reproduce

1- create a form
2- download and active wpgraphql and wp-graphql-gravity-forms
3- in GraphQl playground use a query like this:
  {
    gfSubmittedEntries(where: {formIds: ["21"]}) {
      nodes {
        id
     }
  }
  
 In response i expect to can see, all entries for form 21 as a non-auth user

### Plugin Version

0.12.4

### Gravity Forms Version

2.8.1

### WordPress Version

6.4.2

### WPGraphQL Version

1.20.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [X] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by justlevine** [comment]
Hey @edikamy 

That's default Gravity Forms behavior. You should be able to view the entry _submitted to the mutation_ in the `gfSubmitForm` response.

You should be able to use the [`graphql_gf_can_view_entry` filter](https://github.com/AxeWP/wp-graphql-gravity-forms/blob/develop/docs/actions-and-filters.md#graphql_gf_can_view_entries) to change this default behavior.

Just make sure you're doing some sort of check so you're not showing _all_ users on _all_ entries.

Closing this ticket - if you've got questions on usage, feel free to open a GH Discussion or post in the Slack #gravity-forms channel, or open up a new ticket if you come across any bugs  😎
