### ISSUE TITLE
plugin doesnt use top level vendor folder

### ISSUE THREAD

**Issue by cvanh** [AxeWP/wp-graphql-gravity-forms#439]
### Description

in version 0.13.0 the vendor folder was removed from wp-graphql-gravity-forms and asked developers to download a zip file or run composer install in the plugin folder. 

when installing the plugin using git and packagist the following error appeared 
![image](https://github.com/AxeWP/wp-graphql-gravity-forms/assets/39672378/ab0977ac-324d-4494-9e18-d4dd889213ba)
 

### Steps to reproduce

1. install bedrock
2. run `composer require harness-software/wp-graphql-gravity-forms` in the bedrock project
3. setup bedrock
4. enable wp-graphql-gravity-forms

### Additional context

this was discussed in: https://discord.com/channels/838854618406453300/1257299915655217153

### Plugin Version

0.13.0

### Gravity Forms Version

2.8.7

### WordPress Version

6.3.1

### WPGraphQL Version

1.27.0

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for Gravity Forms, WPGraphQL, and WPGraphQL for Gravity Forms

- [ ] Yes
- [ ] My issue is with a specific 3rd-party plugin.

**Comment by pseelinger** [comment]
I added the `WPGRAPHQL_GF_AUTOLOAD` constant to my environment with a value of `false`, which seems to have fixed this for me. If I'm reading `src/Autloader.php` correctly, this tells the plugin that autoloading is handled elsewhere in the application.
